- hosts: all
  become: yes
  tasks:
    - name: Disable priorities in yum conf to install epel
      become: yes
      copy:
        src: priorities.conf
        dest: /etc/yum/pluginconf.d/priorities.conf
    - name: Enable amazon epel for installing ansible
      shell: "y | amazon-linux-extras install epel"  
      become: yes
    - name: Add gocd yum repo url
      become: yes
      shell: "curl https://download.gocd.org/gocd.repo -o /etc/yum.repos.d/gocd.repo"
    - name: Install go-server
      yum:
        name: go-server
        state: latest
    - name: Install go-agent
      yum:
        name: go-agent
        state: latest
    - name: Install git
      yum:
        name: git
        state: present
        update_cache: yes
    - name: Install ansible
      yum:
        name: ansible
        state: present
    - name: Create directory for storing certs
      file:
        path: /var/go/certs
        state: directory        
    - name: Copy keys to ec2 instance for ansible to use in gocd pipelines
      copy: 
        src: ~/ssh_key
        dest: /var/go/ssh_key
    - name: Copy certs for setting up the website
      copy:
        src: /etc/certs/
        dest: /var/go/certs/
    - name: Restart go-server
      shell: "service go-server start"
      become: yes
    - name: Restart go-agent
      shell: "service go-agent start"
      become: yes      